permalink: /:year/:month/:day/:title.html

# Build settings
markdown: redcarpet
markdown_ext: markdown
highlighter: pygments
# redcarpet config
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify"]


# 作者信息
author: 
  name: ksint
  email: ever4everest@gmail.com
  # link: http://yansu.org
  # twitter: http://weibo.com/yansu0711
  # github: http://github.com/suyan
  twitter_username: Guang_bio
  github_username:  4everer

# 站点信息
title: ksint
description: ksint
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /assets/avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# disqus 设置
disqus:
  shortname: gaugn