permalink: /:year/:month/:day/:title.html

# Build settings
markdown: redcarpet
markdown_ext: markdown
highlighter: pygments
# redcarpet config
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify"]


# Author
author: 
  name: ksint
  email: ever4everest@gmail.com
  # link: http://yansu.org
  # twitter: http://weibo.com/yansu0711
  # github: http://github.com/suyan
  twitter_username: Guang_bio
  github_username:  4everer

# site
title: ksint
description: ksint
rss_url: /pages/atom.xml

# avatar
avatar: /assets/avatar.png

# disqus 设置
disqus:
  shortname: gaugn